spring:
  output:
    ansi:
      enabled: always
  data:
    mongodb:
      host: localhost
      database: books
      username: mongoadmin
      password: mongopass
      authentication-database: admin

mongock:
  start-system-version: 1
  change-logs-scan-package:
    - ru.otus.hw.db.migration
  runner-type: InitializingBean