spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:maindb
  sql:
    init:
      mode: always

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: false

    show-sql: true

  messages:
    encoding: UTF-8
